
/* This file has been automatically generated by the genstroke utility. */

#include "../include/GL/freeglut_internal.h"

/* char: 0x20 */

static const SFG_StrokeStrip ch32st[] =
{
};

static const SFG_StrokeChar ch32 = {104.762,0,ch32st};

/* char: 0x21 */

static const SFG_StrokeVertex ch33st0[] =
{
 {52.381,100},
 {52.381,33.3333}
};

static const SFG_StrokeVertex ch33st1[] =
{
 {52.381,9.5238},
 {47.6191,4.7619},
 {52.381,0},
 {57.1429,4.7619},
 {52.381,9.5238}
};

static const SFG_StrokeStrip ch33st[] =
{
 {2,ch33st0},
 {5,ch33st1}
};

static const SFG_StrokeChar ch33 = {104.762,2,ch33st};

/* char: 0x22 */

static const SFG_StrokeVertex ch34st0[] =
{
 {33.3334,100},
 {33.3334,66.6667}
};

static const SFG_StrokeVertex ch34st1[] =
{
 {71.4286,100},
 {71.4286,66.6667}
};

static const SFG_StrokeStrip ch34st[] =
{
 {2,ch34st0},
 {2,ch34st1}
};

static const SFG_StrokeChar ch34 = {104.762,2,ch34st};

/* char: 0x23 */

static const SFG_StrokeVertex ch35st0[] =
{
 {54.7619,119.048},
 {21.4286,-33.3333}
};

static const SFG_StrokeVertex ch35st1[] =
{
 {83.3334,119.048},
 {50,-33.3333}
};

static const SFG_StrokeVertex ch35st2[] =
{
 {21.4286,57.1429},
 {88.0952,57.1429}
};

static const SFG_StrokeVertex ch35st3[] =
{
 {16.6667,28.5714},
 {83.3334,28.5714}
};

static const SFG_StrokeStrip ch35st[] =
{
 {2,ch35st0},
 {2,ch35st1},
 {2,ch35st2},
 {2,ch35st3}
};

static const SFG_StrokeChar ch35 = {104.762,4,ch35st};

/* char: 0x24 */

static const SFG_StrokeVertex ch36st0[] =
{
 {42.8571,119.048},
 {42.8571,-19.0476}
};

static const SFG_StrokeVertex ch36st1[] =
{
 {61.9047,119.048},
 {61.9047,-19.0476}
};

static const SFG_StrokeVertex ch36st2[] =
{
 {85.7143,85.7143},
 {76.1905,95.2381},
 {61.9047,100},
 {42.8571,100},
 {28.5714,95.2381},
 {19.0476,85.7143},
 {19.0476,76.1905},
 {23.8095,66.6667},
 {28.5714,61.9048},
 {38.0952,57.1429},
 {66.6666,47.619},
 {76.1905,42.8571},
 {80.9524,38.0952},
 {85.7143,28.5714},
 {85.7143,14.2857},
 {76.1905,4.7619},
 {61.9047,0},
 {42.8571,0},
 {28.5714,4.7619},
 {19.0476,14.2857}
};

static const SFG_StrokeStrip ch36st[] =
{
 {2,ch36st0},
 {2,ch36st1},
 {20,ch36st2}
};

static const SFG_StrokeChar ch36 = {104.762,3,ch36st};

/* char: 0x25 */

static const SFG_StrokeVertex ch37st0[] =
{
 {95.2381,100},
 {9.5238,0}
};

static const SFG_StrokeVertex ch37st1[] =
{
 {33.3333,100},
 {42.8571,90.4762},
 {42.8571,80.9524},
 {38.0952,71.4286},
 {28.5714,66.6667},
 {19.0476,66.6667},
 {9.5238,76.1905},
 {9.5238,85.7143},
 {14.2857,95.2381},
 {23.8095,100},
 {33.3333,100},
 {42.8571,95.2381},
 {57.1428,90.4762},
 {71.4286,90.4762},
 {85.7143,95.2381},
 {95.2381,100}
};

static const SFG_StrokeVertex ch37st2[] =
{
 {76.1905,33.3333},
 {66.6667,28.5714},
 {61.9048,19.0476},
 {61.9048,9.5238},
 {71.4286,0},
 {80.9524,0},
 {90.4762,4.7619},
 {95.2381,14.2857},
 {95.2381,23.8095},
 {85.7143,33.3333},
 {76.1905,33.3333}
};

static const SFG_StrokeStrip ch37st[] =
{
 {2,ch37st0},
 {16,ch37st1},
 {11,ch37st2}
};

static const SFG_StrokeChar ch37 = {104.762,3,ch37st};

/* char: 0x26 */

static const SFG_StrokeVertex ch38st0[] =
{
 {100,57.1429},
 {100,61.9048},
 {95.2381,66.6667},
 {90.4762,66.6667},
 {85.7143,61.9048},
 {80.9524,52.381},
 {71.4286,28.5714},
 {61.9048,14.2857},
 {52.3809,4.7619},
 {42.8571,0},
 {23.8095,0},
 {14.2857,4.7619},
 {9.5238,9.5238},
 {4.7619,19.0476},
 {4.7619,28.5714},
 {9.5238,38.0952},
 {14.2857,42.8571},
 {47.619,61.9048},
 {52.3809,66.6667},
 {57.1429,76.1905},
 {57.1429,85.7143},
 {52.3809,95.2381},
 {42.8571,100},
 {33.3333,95.2381},
 {28.5714,85.7143},
 {28.5714,76.1905},
 {33.3333,61.9048},
 {42.8571,47.619},
 {66.6667,14.2857},
 {76.1905,4.7619},
 {85.7143,0},
 {95.2381,0},
 {100,4.7619},
 {100,9.5238}
};

static const SFG_StrokeStrip ch38st[] =
{
 {34,ch38st0}
};

static const SFG_StrokeChar ch38 = {104.762,1,ch38st};

/* char: 0x27 */

static const SFG_StrokeVertex ch39st0[] =
{
 {52.381,100},
 {52.381,66.6667}
};

static const SFG_StrokeStrip ch39st[] =
{
 {2,ch39st0}
};

static const SFG_StrokeChar ch39 = {104.762,1,ch39st};

/* char: 0x28 */

static const SFG_StrokeVertex ch40st0[] =
{
 {69.0476,119.048},
 {59.5238,109.524},
 {50,95.2381},
 {40.4762,76.1905},
 {35.7143,52.381},
 {35.7143,33.3333},
 {40.4762,9.5238},
 {50,-9.5238},
 {59.5238,-23.8095},
 {69.0476,-33.3333}
};

static const SFG_StrokeStrip ch40st[] =
{
 {10,ch40st0}
};

static const SFG_StrokeChar ch40 = {104.762,1,ch40st};

/* char: 0x29 */

static const SFG_StrokeVertex ch41st0[] =
{
 {35.7143,119.048},
 {45.2381,109.524},
 {54.7619,95.2381},
 {64.2857,76.1905},
 {69.0476,52.381},
 {69.0476,33.3333},
 {64.2857,9.5238},
 {54.7619,-9.5238},
 {45.2381,-23.8095},
 {35.7143,-33.3333}
};

static const SFG_StrokeStrip ch41st[] =
{
 {10,ch41st0}
};

static const SFG_StrokeChar ch41 = {104.762,1,ch41st};

/* char: 0x2a */

static const SFG_StrokeVertex ch42st0[] =
{
 {52.381,71.4286},
 {52.381,14.2857}
};

static const SFG_StrokeVertex ch42st1[] =
{
 {28.5715,57.1429},
 {76.1905,28.5714}
};

static const SFG_StrokeVertex ch42st2[] =
{
 {76.1905,57.1429},
 {28.5715,28.5714}
};

static const SFG_StrokeStrip ch42st[] =
{
 {2,ch42st0},
 {2,ch42st1},
 {2,ch42st2}
};

static const SFG_StrokeChar ch42 = {104.762,3,ch42st};

/* char: 0x2b */

static const SFG_StrokeVertex ch43st0[] =
{
 {52.3809,85.7143},
 {52.3809,0}
};

static const SFG_StrokeVertex ch43st1[] =
{
 {9.5238,42.8571},
 {95.2381,42.8571}
};

static const SFG_StrokeStrip ch43st[] =
{
 {2,ch43st0},
 {2,ch43st1}
};

static const SFG_StrokeChar ch43 = {104.762,2,ch43st};

/* char: 0x2c */

static const SFG_StrokeVertex ch44st0[] =
{
 {57.1429,4.7619},
 {52.381,0},
 {47.6191,4.7619},
 {52.381,9.5238},
 {57.1429,4.7619},
 {57.1429,-4.7619},
 {52.381,-14.2857},
 {47.6191,-19.0476}
};

static const SFG_StrokeStrip ch44st[] =
{
 {8,ch44st0}
};

static const SFG_StrokeChar ch44 = {104.762,1,ch44st};

/* char: 0x2d */

static const SFG_StrokeVertex ch45st0[] =
{
 {9.5238,42.8571},
 {95.2381,42.8571}
};

static const SFG_StrokeStrip ch45st[] =
{
 {2,ch45st0}
};

static const SFG_StrokeChar ch45 = {104.762,1,ch45st};

/* char: 0x2e */

static const SFG_StrokeVertex ch46st0[] =
{
 {52.381,9.5238},
 {47.6191,4.7619},
 {52.381,0},
 {57.1429,4.7619},
 {52.381,9.5238}
};

static const SFG_StrokeStrip ch46st[] =
{
 {5,ch46st0}
};

static const SFG_StrokeChar ch46 = {104.762,1,ch46st};

/* char: 0x2f */

static const SFG_StrokeVertex ch47st0[] =
{
 {19.0476,-14.2857},
 {85.7143,100}
};

static const SFG_StrokeStrip ch47st[] =
{
 {2,ch47st0}
};

static const SFG_StrokeChar ch47 = {104.762,1,ch47st};

/* char: 0x30 */

static const SFG_StrokeVertex ch48st0[] =
{
 {47.619,100},
 {33.3333,95.2381},
 {23.8095,80.9524},
 {19.0476,57.1429},
 {19.0476,42.8571},
 {23.8095,19.0476},
 {33.3333,4.7619},
 {47.619,0},
 {57.1428,0},
 {71.4286,4.7619},
 {80.9524,19.0476},
 {85.7143,42.8571},
 {85.7143,57.1429},
 {80.9524,80.9524},
 {71.4286,95.2381},
 {57.1428,100},
 {47.619,100}
};

static const SFG_StrokeStrip ch48st[] =
{
 {17,ch48st0}
};

static const SFG_StrokeChar ch48 = {104.762,1,ch48st};

/* char: 0x31 */

static const SFG_StrokeVertex ch49st0[] =
{
 {40.4762,80.9524},
 {50,85.7143},
 {64.2857,100},
 {64.2857,0}
};

static const SFG_StrokeStrip ch49st[] =
{
 {4,ch49st0}
};

static const SFG_StrokeChar ch49 = {104.762,1,ch49st};

/* char: 0x32 */

static const SFG_StrokeVertex ch50st0[] =
{
 {23.8095,76.1905},
 {23.8095,80.9524},
 {28.5714,90.4762},
 {33.3333,95.2381},
 {42.8571,100},
 {61.9047,100},
 {71.4286,95.2381},
 {76.1905,90.4762},
 {80.9524,80.9524},
 {80.9524,71.4286},
 {76.1905,61.9048},
 {66.6666,47.619},
 {19.0476,0},
 {85.7143,0}
};

static const SFG_StrokeStrip ch50st[] =
{
 {14,ch50st0}
};

static const SFG_StrokeChar ch50 = {104.762,1,ch50st};

/* char: 0x33 */

static const SFG_StrokeVertex ch51st0[] =
{
 {28.5714,100},
 {80.9524,100},
 {52.3809,61.9048},
 {66.6666,61.9048},
 {76.1905,57.1429},
 {80.9524,52.381},
 {85.7143,38.0952},
 {85.7143,28.5714},
 {80.9524,14.2857},
 {71.4286,4.7619},
 {57.1428,0},
 {42.8571,0},
 {28.5714,4.7619},
 {23.8095,9.5238},
 {19.0476,19.0476}
};

static const SFG_StrokeStrip ch51st[] =
{
 {15,ch51st0}
};

static const SFG_StrokeChar ch51 = {104.762,1,ch51st};

/* char: 0x34 */

static const SFG_StrokeVertex ch52st0[] =
{
 {64.2857,100},
 {16.6667,33.3333},
 {88.0952,33.3333}
};

static const SFG_StrokeVertex ch52st1[] =
{
 {64.2857,100},
 {64.2857,0}
};

static const SFG_StrokeStrip ch52st[] =
{
 {3,ch52st0},
 {2,ch52st1}
};

static const SFG_StrokeChar ch52 = {104.762,2,ch52st};

/* char: 0x35 */

static const SFG_StrokeVertex ch53st0[] =
{
 {76.1905,100},
 {28.5714,100},
 {23.8095,57.1429},
 {28.5714,61.9048},
 {42.8571,66.6667},
 {57.1428,66.6667},
 {71.4286,61.9048},
 {80.9524,52.381},
 {85.7143,38.0952},
 {85.7143,28.5714},
 {80.9524,14.2857},
 {71.4286,4.7619},
 {57.1428,0},
 {42.8571,0},
 {28.5714,4.7619},
 {23.8095,9.5238},
 {19.0476,19.0476}
};

static const SFG_StrokeStrip ch53st[] =
{
 {17,ch53st0}
};

static const SFG_StrokeChar ch53 = {104.762,1,ch53st};

/* char: 0x36 */

static const SFG_StrokeVertex ch54st0[] =
{
 {78.5714,85.7143},
 {73.8096,95.2381},
 {59.5238,100},
 {50,100},
 {35.7143,95.2381},
 {26.1905,80.9524},
 {21.4286,57.1429},
 {21.4286,33.3333},
 {26.1905,14.2857},
 {35.7143,4.7619},
 {50,0},
 {54.7619,0},
 {69.0476,4.7619},
 {78.5714,14.2857},
 {83.3334,28.5714},
 {83.3334,33.3333},
 {78.5714,47.619},
 {69.0476,57.1429},
 {54.7619,61.9048},
 {50,61.9048},
 {35.7143,57.1429},
 {26.1905,47.619},
 {21.4286,33.3333}
};

static const SFG_StrokeStrip ch54st[] =
{
 {23,ch54st0}
};

static const SFG_StrokeChar ch54 = {104.762,1,ch54st};

/* char: 0x37 */

static const SFG_StrokeVertex ch55st0[] =
{
 {85.7143,100},
 {38.0952,0}
};

static const SFG_StrokeVertex ch55st1[] =
{
 {19.0476,100},
 {85.7143,100}
};

static const SFG_StrokeStrip ch55st[] =
{
 {2,ch55st0},
 {2,ch55st1}
};

static const SFG_StrokeChar ch55 = {104.762,2,ch55st};

/* char: 0x38 */

static const SFG_StrokeVertex ch56st0[] =
{
 {42.8571,100},
 {28.5714,95.2381},
 {23.8095,85.7143},
 {23.8095,76.1905},
 {28.5714,66.6667},
 {38.0952,61.9048},
 {57.1428,57.1429},
 {71.4286,52.381},
 {80.9524,42.8571},
 {85.7143,33.3333},
 {85.7143,19.0476},
 {80.9524,9.5238},
 {76.1905,4.7619},
 {61.9047,0},
 {42.8571,0},
 {28.5714,4.7619},
 {23.8095,9.5238},
 {19.0476,19.0476},
 {19.0476,33.3333},
 {23.8095,42.8571},
 {33.3333,52.381},
 {47.619,57.1429},
 {66.6666,61.9048},
 {76.1905,66.6667},
 {80.9524,76.1905},
 {80.9524,85.7143},
 {76.1905,95.2381},
 {61.9047,100},
 {42.8571,100}
};

static const SFG_StrokeStrip ch56st[] =
{
 {29,ch56st0}
};

static const SFG_StrokeChar ch56 = {104.762,1,ch56st};

/* char: 0x39 */

static const SFG_StrokeVertex ch57st0[] =
{
 {83.3334,66.6667},
 {78.5714,52.381},
 {69.0476,42.8571},
 {54.7619,38.0952},
 {50,38.0952},
 {35.7143,42.8571},
 {26.1905,52.381},
 {21.4286,66.6667},
 {21.4286,71.4286},
 {26.1905,85.7143},
 {35.7143,95.2381},
 {50,100},
 {54.7619,100},
 {69.0476,95.2381},
 {78.5714,85.7143},
 {83.3334,66.6667},
 {83.3334,42.8571},
 {78.5714,19.0476},
 {69.0476,4.7619},
 {54.7619,0},
 {45.2381,0},
 {30.9524,4.7619},
 {26.1905,14.2857}
};

static const SFG_StrokeStrip ch57st[] =
{
 {23,ch57st0}
};

static const SFG_StrokeChar ch57 = {104.762,1,ch57st};

/* char: 0x3a */

static const SFG_StrokeVertex ch58st0[] =
{
 {52.381,66.6667},
 {47.6191,61.9048},
 {52.381,57.1429},
 {57.1429,61.9048},
 {52.381,66.6667}
};

static const SFG_StrokeVertex ch58st1[] =
{
 {52.381,9.5238},
 {47.6191,4.7619},
 {52.381,0},
 {57.1429,4.7619},
 {52.381,9.5238}
};

static const SFG_StrokeStrip ch58st[] =
{
 {5,ch58st0},
 {5,ch58st1}
};

static const SFG_StrokeChar ch58 = {104.762,2,ch58st};

/* char: 0x3b */

static const SFG_StrokeVertex ch59st0[] =
{
 {52.381,66.6667},
 {47.6191,61.9048},
 {52.381,57.1429},
 {57.1429,61.9048},
 {52.381,66.6667}
};

static const SFG_StrokeVertex ch59st1[] =
{
 {57.1429,4.7619},
 {52.381,0},
 {47.6191,4.7619},
 {52.381,9.5238},
 {57.1429,4.7619},
 {57.1429,-4.7619},
 {52.381,-14.2857},
 {47.6191,-19.0476}
};

static const SFG_StrokeStrip ch59st[] =
{
 {5,ch59st0},
 {8,ch59st1}
};

static const SFG_StrokeChar ch59 = {104.762,2,ch59st};

/* char: 0x3c */

static const SFG_StrokeVertex ch60st0[] =
{
 {90.4762,85.7143},
 {14.2857,42.8571},
 {90.4762,0}
};

static const SFG_StrokeStrip ch60st[] =
{
 {3,ch60st0}
};

static const SFG_StrokeChar ch60 = {104.762,1,ch60st};

/* char: 0x3d */

static const SFG_StrokeVertex ch61st0[] =
{
 {9.5238,57.1429},
 {95.2381,57.1429}
};

static const SFG_StrokeVertex ch61st1[] =
{
 {9.5238,28.5714},
 {95.2381,28.5714}
};

static const SFG_StrokeStrip ch61st[] =
{
 {2,ch61st0},
 {2,ch61st1}
};

static const SFG_StrokeChar ch61 = {104.762,2,ch61st};

/* char: 0x3e */

static const SFG_StrokeVertex ch62st0[] =
{
 {14.2857,85.7143},
 {90.4762,42.8571},
 {14.2857,0}
};

static const SFG_StrokeStrip ch62st[] =
{
 {3,ch62st0}
};

static const SFG_StrokeChar ch62 = {104.762,1,ch62st};

/* char: 0x3f */

static const SFG_StrokeVertex ch63st0[] =
{
 {23.8095,76.1905},
 {23.8095,80.9524},
 {28.5714,90.4762},
 {33.3333,95.2381},
 {42.8571,100},
 {61.9047,100},
 {71.4285,95.2381},
 {76.1905,90.4762},
 {80.9524,80.9524},
 {80.9524,71.4286},
 {76.1905,61.9048},
 {71.4285,57.1429},
 {52.3809,47.619},
 {52.3809,33.3333}
};

static const SFG_StrokeVertex ch63st1[] =
{
 {52.3809,9.5238},
 {47.619,4.7619},
 {52.3809,0},
 {57.1428,4.7619},
 {52.3809,9.5238}
};

static const SFG_StrokeStrip ch63st[] =
{
 {14,ch63st0},
 {5,ch63st1}
};

static const SFG_StrokeChar ch63 = {104.762,2,ch63st};

/* char: 0x40 */

static const SFG_StrokeVertex ch64st0[] =
{
 {64.2857,52.381},
 {54.7619,57.1429},
 {45.2381,57.1429},
 {40.4762,47.619},
 {40.4762,42.8571},
 {45.2381,33.3333},
 {54.7619,33.3333},
 {64.2857,38.0952}
};

static const SFG_StrokeVertex ch64st1[] =
{
 {64.2857,57.1429},
 {64.2857,38.0952},
 {69.0476,33.3333},
 {78.5714,33.3333},
 {83.3334,42.8571},
 {83.3334,47.619},
 {78.5714,61.9048},
 {69.0476,71.4286},
 {54.7619,76.1905},
 {50,76.1905},
 {35.7143,71.4286},
 {26.1905,61.9048},
 {21.4286,47.619},
 {21.4286,42.8571},
 {26.1905,28.5714},
 {35.7143,19.0476},
 {50,14.2857},
 {54.7619,14.2857},
 {69.0476,19.0476}
};

static const SFG_StrokeStrip ch64st[] =
{
 {8,ch64st0},
 {19,ch64st1}
};

static const SFG_StrokeChar ch64 = {104.762,2,ch64st};

/* char: 0x41 */

static const SFG_StrokeVertex ch65st0[] =
{
 {52.3809,100},
 {14.2857,0}
};

static const SFG_StrokeVertex ch65st1[] =
{
 {52.3809,100},
 {90.4762,0}
};

static const SFG_StrokeVertex ch65st2[] =
{
 {28.5714,33.3333},
 {76.1905,33.3333}
};

static const SFG_StrokeStrip ch65st[] =
{
 {2,ch65st0},
 {2,ch65st1},
 {2,ch65st2}
};

static const SFG_StrokeChar ch65 = {104.762,3,ch65st};

/* char: 0x42 */

static const SFG_StrokeVertex ch66st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch66st1[] =
{
 {19.0476,100},
 {61.9047,100},
 {76.1905,95.2381},
 {80.9524,90.4762},
 {85.7143,80.9524},
 {85.7143,71.4286},
 {80.9524,61.9048},
 {76.1905,57.1429},
 {61.9047,52.381}
};

static const SFG_StrokeVertex ch66st2[] =
{
 {19.0476,52.381},
 {61.9047,52.381},
 {76.1905,47.619},
 {80.9524,42.8571},
 {85.7143,33.3333},
 {85.7143,19.0476},
 {80.9524,9.5238},
 {76.1905,4.7619},
 {61.9047,0},
 {19.0476,0}
};

static const SFG_StrokeStrip ch66st[] =
{
 {2,ch66st0},
 {9,ch66st1},
 {10,ch66st2}
};

static const SFG_StrokeChar ch66 = {104.762,3,ch66st};

/* char: 0x43 */

static const SFG_StrokeVertex ch67st0[] =
{
 {88.0952,76.1905},
 {83.3334,85.7143},
 {73.8096,95.2381},
 {64.2857,100},
 {45.2381,100},
 {35.7143,95.2381},
 {26.1905,85.7143},
 {21.4286,76.1905},
 {16.6667,61.9048},
 {16.6667,38.0952},
 {21.4286,23.8095},
 {26.1905,14.2857},
 {35.7143,4.7619},
 {45.2381,0},
 {64.2857,0},
 {73.8096,4.7619},
 {83.3334,14.2857},
 {88.0952,23.8095}
};

static const SFG_StrokeStrip ch67st[] =
{
 {18,ch67st0}
};

static const SFG_StrokeChar ch67 = {104.762,1,ch67st};

/* char: 0x44 */

static const SFG_StrokeVertex ch68st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch68st1[] =
{
 {19.0476,100},
 {52.3809,100},
 {66.6666,95.2381},
 {76.1905,85.7143},
 {80.9524,76.1905},
 {85.7143,61.9048},
 {85.7143,38.0952},
 {80.9524,23.8095},
 {76.1905,14.2857},
 {66.6666,4.7619},
 {52.3809,0},
 {19.0476,0}
};

static const SFG_StrokeStrip ch68st[] =
{
 {2,ch68st0},
 {12,ch68st1}
};

static const SFG_StrokeChar ch68 = {104.762,2,ch68st};

/* char: 0x45 */

static const SFG_StrokeVertex ch69st0[] =
{
 {21.4286,100},
 {21.4286,0}
};

static const SFG_StrokeVertex ch69st1[] =
{
 {21.4286,100},
 {83.3334,100}
};

static const SFG_StrokeVertex ch69st2[] =
{
 {21.4286,52.381},
 {59.5238,52.381}
};

static const SFG_StrokeVertex ch69st3[] =
{
 {21.4286,0},
 {83.3334,0}
};

static const SFG_StrokeStrip ch69st[] =
{
 {2,ch69st0},
 {2,ch69st1},
 {2,ch69st2},
 {2,ch69st3}
};

static const SFG_StrokeChar ch69 = {104.762,4,ch69st};

/* char: 0x46 */

static const SFG_StrokeVertex ch70st0[] =
{
 {21.4286,100},
 {21.4286,0}
};

static const SFG_StrokeVertex ch70st1[] =
{
 {21.4286,100},
 {83.3334,100}
};

static const SFG_StrokeVertex ch70st2[] =
{
 {21.4286,52.381},
 {59.5238,52.381}
};

static const SFG_StrokeStrip ch70st[] =
{
 {2,ch70st0},
 {2,ch70st1},
 {2,ch70st2}
};

static const SFG_StrokeChar ch70 = {104.762,3,ch70st};

/* char: 0x47 */

static const SFG_StrokeVertex ch71st0[] =
{
 {88.0952,76.1905},
 {83.3334,85.7143},
 {73.8096,95.2381},
 {64.2857,100},
 {45.2381,100},
 {35.7143,95.2381},
 {26.1905,85.7143},
 {21.4286,76.1905},
 {16.6667,61.9048},
 {16.6667,38.0952},
 {21.4286,23.8095},
 {26.1905,14.2857},
 {35.7143,4.7619},
 {45.2381,0},
 {64.2857,0},
 {73.8096,4.7619},
 {83.3334,14.2857},
 {88.0952,23.8095},
 {88.0952,38.0952}
};

static const SFG_StrokeVertex ch71st1[] =
{
 {64.2857,38.0952},
 {88.0952,38.0952}
};

static const SFG_StrokeStrip ch71st[] =
{
 {19,ch71st0},
 {2,ch71st1}
};

static const SFG_StrokeChar ch71 = {104.762,2,ch71st};

/* char: 0x48 */

static const SFG_StrokeVertex ch72st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch72st1[] =
{
 {85.7143,100},
 {85.7143,0}
};

static const SFG_StrokeVertex ch72st2[] =
{
 {19.0476,52.381},
 {85.7143,52.381}
};

static const SFG_StrokeStrip ch72st[] =
{
 {2,ch72st0},
 {2,ch72st1},
 {2,ch72st2}
};

static const SFG_StrokeChar ch72 = {104.762,3,ch72st};

/* char: 0x49 */

static const SFG_StrokeVertex ch73st0[] =
{
 {52.381,100},
 {52.381,0}
};

static const SFG_StrokeStrip ch73st[] =
{
 {2,ch73st0}
};

static const SFG_StrokeChar ch73 = {104.762,1,ch73st};

/* char: 0x4a */

static const SFG_StrokeVertex ch74st0[] =
{
 {76.1905,100},
 {76.1905,23.8095},
 {71.4286,9.5238},
 {66.6667,4.7619},
 {57.1429,0},
 {47.6191,0},
 {38.0953,4.7619},
 {33.3334,9.5238},
 {28.5715,23.8095},
 {28.5715,33.3333}
};

static const SFG_StrokeStrip ch74st[] =
{
 {10,ch74st0}
};

static const SFG_StrokeChar ch74 = {104.762,1,ch74st};

/* char: 0x4b */

static const SFG_StrokeVertex ch75st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch75st1[] =
{
 {85.7143,100},
 {19.0476,33.3333}
};

static const SFG_StrokeVertex ch75st2[] =
{
 {42.8571,57.1429},
 {85.7143,0}
};

static const SFG_StrokeStrip ch75st[] =
{
 {2,ch75st0},
 {2,ch75st1},
 {2,ch75st2}
};

static const SFG_StrokeChar ch75 = {104.762,3,ch75st};

/* char: 0x4c */

static const SFG_StrokeVertex ch76st0[] =
{
 {23.8095,100},
 {23.8095,0}
};

static const SFG_StrokeVertex ch76st1[] =
{
 {23.8095,0},
 {80.9524,0}
};

static const SFG_StrokeStrip ch76st[] =
{
 {2,ch76st0},
 {2,ch76st1}
};

static const SFG_StrokeChar ch76 = {104.762,2,ch76st};

/* char: 0x4d */

static const SFG_StrokeVertex ch77st0[] =
{
 {14.2857,100},
 {14.2857,0}
};

static const SFG_StrokeVertex ch77st1[] =
{
 {14.2857,100},
 {52.3809,0}
};

static const SFG_StrokeVertex ch77st2[] =
{
 {90.4762,100},
 {52.3809,0}
};

static const SFG_StrokeVertex ch77st3[] =
{
 {90.4762,100},
 {90.4762,0}
};

static const SFG_StrokeStrip ch77st[] =
{
 {2,ch77st0},
 {2,ch77st1},
 {2,ch77st2},
 {2,ch77st3}
};

static const SFG_StrokeChar ch77 = {104.762,4,ch77st};

/* char: 0x4e */

static const SFG_StrokeVertex ch78st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch78st1[] =
{
 {19.0476,100},
 {85.7143,0}
};

static const SFG_StrokeVertex ch78st2[] =
{
 {85.7143,100},
 {85.7143,0}
};

static const SFG_StrokeStrip ch78st[] =
{
 {2,ch78st0},
 {2,ch78st1},
 {2,ch78st2}
};

static const SFG_StrokeChar ch78 = {104.762,3,ch78st};

/* char: 0x4f */

static const SFG_StrokeVertex ch79st0[] =
{
 {42.8571,100},
 {33.3333,95.2381},
 {23.8095,85.7143},
 {19.0476,76.1905},
 {14.2857,61.9048},
 {14.2857,38.0952},
 {19.0476,23.8095},
 {23.8095,14.2857},
 {33.3333,4.7619},
 {42.8571,0},
 {61.9047,0},
 {71.4286,4.7619},
 {80.9524,14.2857},
 {85.7143,23.8095},
 {90.4762,38.0952},
 {90.4762,61.9048},
 {85.7143,76.1905},
 {80.9524,85.7143},
 {71.4286,95.2381},
 {61.9047,100},
 {42.8571,100}
};

static const SFG_StrokeStrip ch79st[] =
{
 {21,ch79st0}
};

static const SFG_StrokeChar ch79 = {104.762,1,ch79st};

/* char: 0x50 */

static const SFG_StrokeVertex ch80st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch80st1[] =
{
 {19.0476,100},
 {61.9047,100},
 {76.1905,95.2381},
 {80.9524,90.4762},
 {85.7143,80.9524},
 {85.7143,66.6667},
 {80.9524,57.1429},
 {76.1905,52.381},
 {61.9047,47.619},
 {19.0476,47.619}
};

static const SFG_StrokeStrip ch80st[] =
{
 {2,ch80st0},
 {10,ch80st1}
};

static const SFG_StrokeChar ch80 = {104.762,2,ch80st};

/* char: 0x51 */

static const SFG_StrokeVertex ch81st0[] =
{
 {42.8571,100},
 {33.3333,95.2381},
 {23.8095,85.7143},
 {19.0476,76.1905},
 {14.2857,61.9048},
 {14.2857,38.0952},
 {19.0476,23.8095},
 {23.8095,14.2857},
 {33.3333,4.7619},
 {42.8571,0},
 {61.9047,0},
 {71.4286,4.7619},
 {80.9524,14.2857},
 {85.7143,23.8095},
 {90.4762,38.0952},
 {90.4762,61.9048},
 {85.7143,76.1905},
 {80.9524,85.7143},
 {71.4286,95.2381},
 {61.9047,100},
 {42.8571,100}
};

static const SFG_StrokeVertex ch81st1[] =
{
 {57.1428,19.0476},
 {85.7143,-9.5238}
};

static const SFG_StrokeStrip ch81st[] =
{
 {21,ch81st0},
 {2,ch81st1}
};

static const SFG_StrokeChar ch81 = {104.762,2,ch81st};

/* char: 0x52 */

static const SFG_StrokeVertex ch82st0[] =
{
 {19.0476,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch82st1[] =
{
 {19.0476,100},
 {61.9047,100},
 {76.1905,95.2381},
 {80.9524,90.4762},
 {85.7143,80.9524},
 {85.7143,71.4286},
 {80.9524,61.9048},
 {76.1905,57.1429},
 {61.9047,52.381},
 {19.0476,52.381}
};

static const SFG_StrokeVertex ch82st2[] =
{
 {52.3809,52.381},
 {85.7143,0}
};

static const SFG_StrokeStrip ch82st[] =
{
 {2,ch82st0},
 {10,ch82st1},
 {2,ch82st2}
};

static const SFG_StrokeChar ch82 = {104.762,3,ch82st};

/* char: 0x53 */

static const SFG_StrokeVertex ch83st0[] =
{
 {85.7143,85.7143},
 {76.1905,95.2381},
 {61.9047,100},
 {42.8571,100},
 {28.5714,95.2381},
 {19.0476,85.7143},
 {19.0476,76.1905},
 {23.8095,66.6667},
 {28.5714,61.9048},
 {38.0952,57.1429},
 {66.6666,47.619},
 {76.1905,42.8571},
 {80.9524,38.0952},
 {85.7143,28.5714},
 {85.7143,14.2857},
 {76.1905,4.7619},
 {61.9047,0},
 {42.8571,0},
 {28.5714,4.7619},
 {19.0476,14.2857}
};

static const SFG_StrokeStrip ch83st[] =
{
 {20,ch83st0}
};

static const SFG_StrokeChar ch83 = {104.762,1,ch83st};

/* char: 0x54 */

static const SFG_StrokeVertex ch84st0[] =
{
 {52.3809,100},
 {52.3809,0}
};

static const SFG_StrokeVertex ch84st1[] =
{
 {19.0476,100},
 {85.7143,100}
};

static const SFG_StrokeStrip ch84st[] =
{
 {2,ch84st0},
 {2,ch84st1}
};

static const SFG_StrokeChar ch84 = {104.762,2,ch84st};

/* char: 0x55 */

static const SFG_StrokeVertex ch85st0[] =
{
 {19.0476,100},
 {19.0476,28.5714},
 {23.8095,14.2857},
 {33.3333,4.7619},
 {47.619,0},
 {57.1428,0},
 {71.4286,4.7619},
 {80.9524,14.2857},
 {85.7143,28.5714},
 {85.7143,100}
};

static const SFG_StrokeStrip ch85st[] =
{
 {10,ch85st0}
};

static const SFG_StrokeChar ch85 = {104.762,1,ch85st};

/* char: 0x56 */

static const SFG_StrokeVertex ch86st0[] =
{
 {14.2857,100},
 {52.3809,0}
};

static const SFG_StrokeVertex ch86st1[] =
{
 {90.4762,100},
 {52.3809,0}
};

static const SFG_StrokeStrip ch86st[] =
{
 {2,ch86st0},
 {2,ch86st1}
};

static const SFG_StrokeChar ch86 = {104.762,2,ch86st};

/* char: 0x57 */

static const SFG_StrokeVertex ch87st0[] =
{
 {4.7619,100},
 {28.5714,0}
};

static const SFG_StrokeVertex ch87st1[] =
{
 {52.3809,100},
 {28.5714,0}
};

static const SFG_StrokeVertex ch87st2[] =
{
 {52.3809,100},
 {76.1905,0}
};

static const SFG_StrokeVertex ch87st3[] =
{
 {100,100},
 {76.1905,0}
};

static const SFG_StrokeStrip ch87st[] =
{
 {2,ch87st0},
 {2,ch87st1},
 {2,ch87st2},
 {2,ch87st3}
};

static const SFG_StrokeChar ch87 = {104.762,4,ch87st};

/* char: 0x58 */

static const SFG_StrokeVertex ch88st0[] =
{
 {19.0476,100},
 {85.7143,0}
};

static const SFG_StrokeVertex ch88st1[] =
{
 {85.7143,100},
 {19.0476,0}
};

static const SFG_StrokeStrip ch88st[] =
{
 {2,ch88st0},
 {2,ch88st1}
};

static const SFG_StrokeChar ch88 = {104.762,2,ch88st};

/* char: 0x59 */

static const SFG_StrokeVertex ch89st0[] =
{
 {14.2857,100},
 {52.3809,52.381},
 {52.3809,0}
};

static const SFG_StrokeVertex ch89st1[] =
{
 {90.4762,100},
 {52.3809,52.381}
};

static const SFG_StrokeStrip ch89st[] =
{
 {3,ch89st0},
 {2,ch89st1}
};

static const SFG_StrokeChar ch89 = {104.762,2,ch89st};

/* char: 0x5a */

static const SFG_StrokeVertex ch90st0[] =
{
 {85.7143,100},
 {19.0476,0}
};

static const SFG_StrokeVertex ch90st1[] =
{
 {19.0476,100},
 {85.7143,100}
};

static const SFG_StrokeVertex ch90st2[] =
{
 {19.0476,0},
 {85.7143,0}
};

static const SFG_StrokeStrip ch90st[] =
{
 {2,ch90st0},
 {2,ch90st1},
 {2,ch90st2}
};

static const SFG_StrokeChar ch90 = {104.762,3,ch90st};

/* char: 0x5b */

static const SFG_StrokeVertex ch91st0[] =
{
 {35.7143,119.048},
 {35.7143,-33.3333}
};

static const SFG_StrokeVertex ch91st1[] =
{
 {40.4762,119.048},
 {40.4762,-33.3333}
};

static const SFG_StrokeVertex ch91st2[] =
{
 {35.7143,119.048},
 {69.0476,119.048}
};

static const SFG_StrokeVertex ch91st3[] =
{
 {35.7143,-33.3333},
 {69.0476,-33.3333}
};

static const SFG_StrokeStrip ch91st[] =
{
 {2,ch91st0},
 {2,ch91st1},
 {2,ch91st2},
 {2,ch91st3}
};

static const SFG_StrokeChar ch91 = {104.762,4,ch91st};

/* char: 0x5c */

static const SFG_StrokeVertex ch92st0[] =
{
 {19.0476,100},
 {85.7143,-14.2857}
};

static const SFG_StrokeStrip ch92st[] =
{
 {2,ch92st0}
};

static const SFG_StrokeChar ch92 = {104.762,1,ch92st};

/* char: 0x5d */

static const SFG_StrokeVertex ch93st0[] =
{
 {64.2857,119.048},
 {64.2857,-33.3333}
};

static const SFG_StrokeVertex ch93st1[] =
{
 {69.0476,119.048},
 {69.0476,-33.3333}
};

static const SFG_StrokeVertex ch93st2[] =
{
 {35.7143,119.048},
 {69.0476,119.048}
};

static const SFG_StrokeVertex ch93st3[] =
{
 {35.7143,-33.3333},
 {69.0476,-33.3333}
};

static const SFG_StrokeStrip ch93st[] =
{
 {2,ch93st0},
 {2,ch93st1},
 {2,ch93st2},
 {2,ch93st3}
};

static const SFG_StrokeChar ch93 = {104.762,4,ch93st};

/* char: 0x5e */

static const SFG_StrokeVertex ch94st0[] =
{
 {52.3809,109.524},
 {14.2857,42.8571}
};

static const SFG_StrokeVertex ch94st1[] =
{
 {52.3809,109.524},
 {90.4762,42.8571}
};

static const SFG_StrokeStrip ch94st[] =
{
 {2,ch94st0},
 {2,ch94st1}
};

static const SFG_StrokeChar ch94 = {104.762,2,ch94st};

/* char: 0x5f */

static const SFG_StrokeVertex ch95st0[] =
{
 {0,-33.3333},
 {104.762,-33.3333},
 {104.762,-28.5714},
 {0,-28.5714},
 {0,-33.3333}
};

static const SFG_StrokeStrip ch95st[] =
{
 {5,ch95st0}
};

static const SFG_StrokeChar ch95 = {104.762,1,ch95st};

/* char: 0x60 */

static const SFG_StrokeVertex ch96st0[] =
{
 {42.8572,100},
 {66.6667,71.4286}
};

static const SFG_StrokeVertex ch96st1[] =
{
 {42.8572,100},
 {38.0953,95.2381},
 {66.6667,71.4286}
};

static const SFG_StrokeStrip ch96st[] =
{
 {2,ch96st0},
 {3,ch96st1}
};

static const SFG_StrokeChar ch96 = {104.762,2,ch96st};

/* char: 0x61 */

static const SFG_StrokeVertex ch97st0[] =
{
 {80.9524,66.6667},
 {80.9524,0}
};

static const SFG_StrokeVertex ch97st1[] =
{
 {80.9524,52.381},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch97st[] =
{
 {2,ch97st0},
 {14,ch97st1}
};

static const SFG_StrokeChar ch97 = {104.762,2,ch97st};

/* char: 0x62 */

static const SFG_StrokeVertex ch98st0[] =
{
 {23.8095,100},
 {23.8095,0}
};

static const SFG_StrokeVertex ch98st1[] =
{
 {23.8095,52.381},
 {33.3333,61.9048},
 {42.8571,66.6667},
 {57.1428,66.6667},
 {66.6666,61.9048},
 {76.1905,52.381},
 {80.9524,38.0952},
 {80.9524,28.5714},
 {76.1905,14.2857},
 {66.6666,4.7619},
 {57.1428,0},
 {42.8571,0},
 {33.3333,4.7619},
 {23.8095,14.2857}
};

static const SFG_StrokeStrip ch98st[] =
{
 {2,ch98st0},
 {14,ch98st1}
};

static const SFG_StrokeChar ch98 = {104.762,2,ch98st};

/* char: 0x63 */

static const SFG_StrokeVertex ch99st0[] =
{
 {80.9524,52.381},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch99st[] =
{
 {14,ch99st0}
};

static const SFG_StrokeChar ch99 = {104.762,1,ch99st};

/* char: 0x64 */

static const SFG_StrokeVertex ch100st0[] =
{
 {80.9524,100},
 {80.9524,0}
};

static const SFG_StrokeVertex ch100st1[] =
{
 {80.9524,52.381},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch100st[] =
{
 {2,ch100st0},
 {14,ch100st1}
};

static const SFG_StrokeChar ch100 = {104.762,2,ch100st};

/* char: 0x65 */

static const SFG_StrokeVertex ch101st0[] =
{
 {23.8095,38.0952},
 {80.9524,38.0952},
 {80.9524,47.619},
 {76.1905,57.1429},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch101st[] =
{
 {17,ch101st0}
};

static const SFG_StrokeChar ch101 = {104.762,1,ch101st};

/* char: 0x66 */

static const SFG_StrokeVertex ch102st0[] =
{
 {71.4286,100},
 {61.9048,100},
 {52.381,95.2381},
 {47.6191,80.9524},
 {47.6191,0}
};

static const SFG_StrokeVertex ch102st1[] =
{
 {33.3334,66.6667},
 {66.6667,66.6667}
};

static const SFG_StrokeStrip ch102st[] =
{
 {5,ch102st0},
 {2,ch102st1}
};

static const SFG_StrokeChar ch102 = {104.762,2,ch102st};

/* char: 0x67 */

static const SFG_StrokeVertex ch103st0[] =
{
 {80.9524,66.6667},
 {80.9524,-9.5238},
 {76.1905,-23.8095},
 {71.4285,-28.5714},
 {61.9047,-33.3333},
 {47.619,-33.3333},
 {38.0952,-28.5714}
};

static const SFG_StrokeVertex ch103st1[] =
{
 {80.9524,52.381},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch103st[] =
{
 {7,ch103st0},
 {14,ch103st1}
};

static const SFG_StrokeChar ch103 = {104.762,2,ch103st};

/* char: 0x68 */

static const SFG_StrokeVertex ch104st0[] =
{
 {26.1905,100},
 {26.1905,0}
};

static const SFG_StrokeVertex ch104st1[] =
{
 {26.1905,47.619},
 {40.4762,61.9048},
 {50,66.6667},
 {64.2857,66.6667},
 {73.8095,61.9048},
 {78.5715,47.619},
 {78.5715,0}
};

static const SFG_StrokeStrip ch104st[] =
{
 {2,ch104st0},
 {7,ch104st1}
};

static const SFG_StrokeChar ch104 = {104.762,2,ch104st};

/* char: 0x69 */

static const SFG_StrokeVertex ch105st0[] =
{
 {47.6191,100},
 {52.381,95.2381},
 {57.1429,100},
 {52.381,104.762},
 {47.6191,100}
};

static const SFG_StrokeVertex ch105st1[] =
{
 {52.381,66.6667},
 {52.381,0}
};

static const SFG_StrokeStrip ch105st[] =
{
 {5,ch105st0},
 {2,ch105st1}
};

static const SFG_StrokeChar ch105 = {104.762,2,ch105st};

/* char: 0x6a */

static const SFG_StrokeVertex ch106st0[] =
{
 {57.1429,100},
 {61.9048,95.2381},
 {66.6667,100},
 {61.9048,104.762},
 {57.1429,100}
};

static const SFG_StrokeVertex ch106st1[] =
{
 {61.9048,66.6667},
 {61.9048,-14.2857},
 {57.1429,-28.5714},
 {47.6191,-33.3333},
 {38.0953,-33.3333}
};

static const SFG_StrokeStrip ch106st[] =
{
 {5,ch106st0},
 {5,ch106st1}
};

static const SFG_StrokeChar ch106 = {104.762,2,ch106st};

/* char: 0x6b */

static const SFG_StrokeVertex ch107st0[] =
{
 {26.1905,100},
 {26.1905,0}
};

static const SFG_StrokeVertex ch107st1[] =
{
 {73.8095,66.6667},
 {26.1905,19.0476}
};

static const SFG_StrokeVertex ch107st2[] =
{
 {45.2381,38.0952},
 {78.5715,0}
};

static const SFG_StrokeStrip ch107st[] =
{
 {2,ch107st0},
 {2,ch107st1},
 {2,ch107st2}
};

static const SFG_StrokeChar ch107 = {104.762,3,ch107st};

/* char: 0x6c */

static const SFG_StrokeVertex ch108st0[] =
{
 {52.381,100},
 {52.381,0}
};

static const SFG_StrokeStrip ch108st[] =
{
 {2,ch108st0}
};

static const SFG_StrokeChar ch108 = {104.762,1,ch108st};

/* char: 0x6d */

static const SFG_StrokeVertex ch109st0[] =
{
 {0,66.6667},
 {0,0}
};

static const SFG_StrokeVertex ch109st1[] =
{
 {0,47.619},
 {14.2857,61.9048},
 {23.8095,66.6667},
 {38.0952,66.6667},
 {47.619,61.9048},
 {52.381,47.619},
 {52.381,0}
};

static const SFG_StrokeVertex ch109st2[] =
{
 {52.381,47.619},
 {66.6667,61.9048},
 {76.1905,66.6667},
 {90.4762,66.6667},
 {100,61.9048},
 {104.762,47.619},
 {104.762,0}
};

static const SFG_StrokeStrip ch109st[] =
{
 {2,ch109st0},
 {7,ch109st1},
 {7,ch109st2}
};

static const SFG_StrokeChar ch109 = {104.762,3,ch109st};

/* char: 0x6e */

static const SFG_StrokeVertex ch110st0[] =
{
 {26.1905,66.6667},
 {26.1905,0}
};

static const SFG_StrokeVertex ch110st1[] =
{
 {26.1905,47.619},
 {40.4762,61.9048},
 {50,66.6667},
 {64.2857,66.6667},
 {73.8095,61.9048},
 {78.5715,47.619},
 {78.5715,0}
};

static const SFG_StrokeStrip ch110st[] =
{
 {2,ch110st0},
 {7,ch110st1}
};

static const SFG_StrokeChar ch110 = {104.762,2,ch110st};

/* char: 0x6f */

static const SFG_StrokeVertex ch111st0[] =
{
 {45.2381,66.6667},
 {35.7143,61.9048},
 {26.1905,52.381},
 {21.4286,38.0952},
 {21.4286,28.5714},
 {26.1905,14.2857},
 {35.7143,4.7619},
 {45.2381,0},
 {59.5238,0},
 {69.0476,4.7619},
 {78.5714,14.2857},
 {83.3334,28.5714},
 {83.3334,38.0952},
 {78.5714,52.381},
 {69.0476,61.9048},
 {59.5238,66.6667},
 {45.2381,66.6667}
};

static const SFG_StrokeStrip ch111st[] =
{
 {17,ch111st0}
};

static const SFG_StrokeChar ch111 = {104.762,1,ch111st};

/* char: 0x70 */

static const SFG_StrokeVertex ch112st0[] =
{
 {23.8095,66.6667},
 {23.8095,-33.3333}
};

static const SFG_StrokeVertex ch112st1[] =
{
 {23.8095,52.381},
 {33.3333,61.9048},
 {42.8571,66.6667},
 {57.1428,66.6667},
 {66.6666,61.9048},
 {76.1905,52.381},
 {80.9524,38.0952},
 {80.9524,28.5714},
 {76.1905,14.2857},
 {66.6666,4.7619},
 {57.1428,0},
 {42.8571,0},
 {33.3333,4.7619},
 {23.8095,14.2857}
};

static const SFG_StrokeStrip ch112st[] =
{
 {2,ch112st0},
 {14,ch112st1}
};

static const SFG_StrokeChar ch112 = {104.762,2,ch112st};

/* char: 0x71 */

static const SFG_StrokeVertex ch113st0[] =
{
 {80.9524,66.6667},
 {80.9524,-33.3333}
};

static const SFG_StrokeVertex ch113st1[] =
{
 {80.9524,52.381},
 {71.4285,61.9048},
 {61.9047,66.6667},
 {47.619,66.6667},
 {38.0952,61.9048},
 {28.5714,52.381},
 {23.8095,38.0952},
 {23.8095,28.5714},
 {28.5714,14.2857},
 {38.0952,4.7619},
 {47.619,0},
 {61.9047,0},
 {71.4285,4.7619},
 {80.9524,14.2857}
};

static const SFG_StrokeStrip ch113st[] =
{
 {2,ch113st0},
 {14,ch113st1}
};

static const SFG_StrokeChar ch113 = {104.762,2,ch113st};

/* char: 0x72 */

static const SFG_StrokeVertex ch114st0[] =
{
 {33.3334,66.6667},
 {33.3334,0}
};

static const SFG_StrokeVertex ch114st1[] =
{
 {33.3334,38.0952},
 {38.0953,52.381},
 {47.6191,61.9048},
 {57.1429,66.6667},
 {71.4286,66.6667}
};

static const SFG_StrokeStrip ch114st[] =
{
 {2,ch114st0},
 {5,ch114st1}
};

static const SFG_StrokeChar ch114 = {104.762,2,ch114st};

/* char: 0x73 */

static const SFG_StrokeVertex ch115st0[] =
{
 {78.5715,52.381},
 {73.8095,61.9048},
 {59.5238,66.6667},
 {45.2381,66.6667},
 {30.9524,61.9048},
 {26.1905,52.381},
 {30.9524,42.8571},
 {40.4762,38.0952},
 {64.2857,33.3333},
 {73.8095,28.5714},
 {78.5715,19.0476},
 {78.5715,14.2857},
 {73.8095,4.7619},
 {59.5238,0},
 {45.2381,0},
 {30.9524,4.7619},
 {26.1905,14.2857}
};

static const SFG_StrokeStrip ch115st[] =
{
 {17,ch115st0}
};

static const SFG_StrokeChar ch115 = {104.762,1,ch115st};

/* char: 0x74 */

static const SFG_StrokeVertex ch116st0[] =
{
 {47.6191,100},
 {47.6191,19.0476},
 {52.381,4.7619},
 {61.9048,0},
 {71.4286,0}
};

static const SFG_StrokeVertex ch116st1[] =
{
 {33.3334,66.6667},
 {66.6667,66.6667}
};

static const SFG_StrokeStrip ch116st[] =
{
 {5,ch116st0},
 {2,ch116st1}
};

static const SFG_StrokeChar ch116 = {104.762,2,ch116st};

/* char: 0x75 */

static const SFG_StrokeVertex ch117st0[] =
{
 {26.1905,66.6667},
 {26.1905,19.0476},
 {30.9524,4.7619},
 {40.4762,0},
 {54.7619,0},
 {64.2857,4.7619},
 {78.5715,19.0476}
};

static const SFG_StrokeVertex ch117st1[] =
{
 {78.5715,66.6667},
 {78.5715,0}
};

static const SFG_StrokeStrip ch117st[] =
{
 {7,ch117st0},
 {2,ch117st1}
};

static const SFG_StrokeChar ch117 = {104.762,2,ch117st};

/* char: 0x76 */

static const SFG_StrokeVertex ch118st0[] =
{
 {23.8095,66.6667},
 {52.3809,0}
};

static const SFG_StrokeVertex ch118st1[] =
{
 {80.9524,66.6667},
 {52.3809,0}
};

static const SFG_StrokeStrip ch118st[] =
{
 {2,ch118st0},
 {2,ch118st1}
};

static const SFG_StrokeChar ch118 = {104.762,2,ch118st};

/* char: 0x77 */

static const SFG_StrokeVertex ch119st0[] =
{
 {14.2857,66.6667},
 {33.3333,0}
};

static const SFG_StrokeVertex ch119st1[] =
{
 {52.3809,66.6667},
 {33.3333,0}
};

static const SFG_StrokeVertex ch119st2[] =
{
 {52.3809,66.6667},
 {71.4286,0}
};

static const SFG_StrokeVertex ch119st3[] =
{
 {90.4762,66.6667},
 {71.4286,0}
};

static const SFG_StrokeStrip ch119st[] =
{
 {2,ch119st0},
 {2,ch119st1},
 {2,ch119st2},
 {2,ch119st3}
};

static const SFG_StrokeChar ch119 = {104.762,4,ch119st};

/* char: 0x78 */

static const SFG_StrokeVertex ch120st0[] =
{
 {26.1905,66.6667},
 {78.5715,0}
};

static const SFG_StrokeVertex ch120st1[] =
{
 {78.5715,66.6667},
 {26.1905,0}
};

static const SFG_StrokeStrip ch120st[] =
{
 {2,ch120st0},
 {2,ch120st1}
};

static const SFG_StrokeChar ch120 = {104.762,2,ch120st};

/* char: 0x79 */

static const SFG_StrokeVertex ch121st0[] =
{
 {26.1905,66.6667},
 {54.7619,0}
};

static const SFG_StrokeVertex ch121st1[] =
{
 {83.3334,66.6667},
 {54.7619,0},
 {45.2381,-19.0476},
 {35.7143,-28.5714},
 {26.1905,-33.3333},
 {21.4286,-33.3333}
};

static const SFG_StrokeStrip ch121st[] =
{
 {2,ch121st0},
 {6,ch121st1}
};

static const SFG_StrokeChar ch121 = {104.762,2,ch121st};

/* char: 0x7a */

static const SFG_StrokeVertex ch122st0[] =
{
 {78.5715,66.6667},
 {26.1905,0}
};

static const SFG_StrokeVertex ch122st1[] =
{
 {26.1905,66.6667},
 {78.5715,66.6667}
};

static const SFG_StrokeVertex ch122st2[] =
{
 {26.1905,0},
 {78.5715,0}
};

static const SFG_StrokeStrip ch122st[] =
{
 {2,ch122st0},
 {2,ch122st1},
 {2,ch122st2}
};

static const SFG_StrokeChar ch122 = {104.762,3,ch122st};

/* char: 0x7b */

static const SFG_StrokeVertex ch123st0[] =
{
 {64.2857,119.048},
 {54.7619,114.286},
 {50,109.524},
 {45.2381,100},
 {45.2381,90.4762},
 {50,80.9524},
 {54.7619,76.1905},
 {59.5238,66.6667},
 {59.5238,57.1429},
 {50,47.619}
};

static const SFG_StrokeVertex ch123st1[] =
{
 {54.7619,114.286},
 {50,104.762},
 {50,95.2381},
 {54.7619,85.7143},
 {59.5238,80.9524},
 {64.2857,71.4286},
 {64.2857,61.9048},
 {59.5238,52.381},
 {40.4762,42.8571},
 {59.5238,33.3333},
 {64.2857,23.8095},
 {64.2857,14.2857},
 {59.5238,4.7619},
 {54.7619,0},
 {50,-9.5238},
 {50,-19.0476},
 {54.7619,-28.5714}
};

static const SFG_StrokeVertex ch123st2[] =
{
 {50,38.0952},
 {59.5238,28.5714},
 {59.5238,19.0476},
 {54.7619,9.5238},
 {50,4.7619},
 {45.2381,-4.7619},
 {45.2381,-14.2857},
 {50,-23.8095},
 {54.7619,-28.5714},
 {64.2857,-33.3333}
};

static const SFG_StrokeStrip ch123st[] =
{
 {10,ch123st0},
 {17,ch123st1},
 {10,ch123st2}
};

static const SFG_StrokeChar ch123 = {104.762,3,ch123st};

/* char: 0x7c */

static const SFG_StrokeVertex ch124st0[] =
{
 {52.381,119.048},
 {52.381,-33.3333}
};

static const SFG_StrokeStrip ch124st[] =
{
 {2,ch124st0}
};

static const SFG_StrokeChar ch124 = {104.762,1,ch124st};

/* char: 0x7d */

static const SFG_StrokeVertex ch125st0[] =
{
 {40.4762,119.048},
 {50,114.286},
 {54.7619,109.524},
 {59.5238,100},
 {59.5238,90.4762},
 {54.7619,80.9524},
 {50,76.1905},
 {45.2381,66.6667},
 {45.2381,57.1429},
 {54.7619,47.619}
};

static const SFG_StrokeVertex ch125st1[] =
{
 {50,114.286},
 {54.7619,104.762},
 {54.7619,95.2381},
 {50,85.7143},
 {45.2381,80.9524},
 {40.4762,71.4286},
 {40.4762,61.9048},
 {45.2381,52.381},
 {64.2857,42.8571},
 {45.2381,33.3333},
 {40.4762,23.8095},
 {40.4762,14.2857},
 {45.2381,4.7619},
 {50,0},
 {54.7619,-9.5238},
 {54.7619,-19.0476},
 {50,-28.5714}
};

static const SFG_StrokeVertex ch125st2[] =
{
 {54.7619,38.0952},
 {45.2381,28.5714},
 {45.2381,19.0476},
 {50,9.5238},
 {54.7619,4.7619},
 {59.5238,-4.7619},
 {59.5238,-14.2857},
 {54.7619,-23.8095},
 {50,-28.5714},
 {40.4762,-33.3333}
};

static const SFG_StrokeStrip ch125st[] =
{
 {10,ch125st0},
 {17,ch125st1},
 {10,ch125st2}
};

static const SFG_StrokeChar ch125 = {104.762,3,ch125st};

/* char: 0x7e */

static const SFG_StrokeVertex ch126st0[] =
{
 {9.5238,28.5714},
 {9.5238,38.0952},
 {14.2857,52.381},
 {23.8095,57.1429},
 {33.3333,57.1429},
 {42.8571,52.381},
 {61.9048,38.0952},
 {71.4286,33.3333},
 {80.9524,33.3333},
 {90.4762,38.0952},
 {95.2381,47.619}
};

static const SFG_StrokeVertex ch126st1[] =
{
 {9.5238,38.0952},
 {14.2857,47.619},
 {23.8095,52.381},
 {33.3333,52.381},
 {42.8571,47.619},
 {61.9048,33.3333},
 {71.4286,28.5714},
 {80.9524,28.5714},
 {90.4762,33.3333},
 {95.2381,47.619},
 {95.2381,57.1429}
};

static const SFG_StrokeStrip ch126st[] =
{
 {11,ch126st0},
 {11,ch126st1}
};

static const SFG_StrokeChar ch126 = {104.762,2,ch126st};

/* char: 0x7f */

static const SFG_StrokeVertex ch127st0[] =
{
 {71.4286,100},
 {33.3333,-33.3333}
};

static const SFG_StrokeVertex ch127st1[] =
{
 {47.619,66.6667},
 {33.3333,61.9048},
 {23.8095,52.381},
 {19.0476,38.0952},
 {19.0476,23.8095},
 {23.8095,14.2857},
 {33.3333,4.7619},
 {47.619,0},
 {57.1428,0},
 {71.4286,4.7619},
 {80.9524,14.2857},
 {85.7143,28.5714},
 {85.7143,42.8571},
 {80.9524,52.381},
 {71.4286,61.9048},
 {57.1428,66.6667},
 {47.619,66.6667}
};

static const SFG_StrokeStrip ch127st[] =
{
 {2,ch127st0},
 {17,ch127st1}
};

static const SFG_StrokeChar ch127 = {104.762,2,ch127st};

static const SFG_StrokeChar *chars[] =
{
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0,
 &ch32, &ch33, &ch34, &ch35, &ch36, &ch37, &ch38, &ch39,
 &ch40, &ch41, &ch42, &ch43, &ch44, &ch45, &ch46, &ch47,
 &ch48, &ch49, &ch50, &ch51, &ch52, &ch53, &ch54, &ch55,
 &ch56, &ch57, &ch58, &ch59, &ch60, &ch61, &ch62, &ch63,
 &ch64, &ch65, &ch66, &ch67, &ch68, &ch69, &ch70, &ch71,
 &ch72, &ch73, &ch74, &ch75, &ch76, &ch77, &ch78, &ch79,
 &ch80, &ch81, &ch82, &ch83, &ch84, &ch85, &ch86, &ch87,
 &ch88, &ch89, &ch90, &ch91, &ch92, &ch93, &ch94, &ch95,
 &ch96, &ch97, &ch98, &ch99, &ch100, &ch101, &ch102, &ch103,
 &ch104, &ch105, &ch106, &ch107, &ch108, &ch109, &ch110, &ch111,
 &ch112, &ch113, &ch114, &ch115, &ch116, &ch117, &ch118, &ch119,
 &ch120, &ch121, &ch122, &ch123, &ch124, &ch125, &ch126, &ch127
};

const SFG_StrokeFont fgStrokeMonoRoman = {"MonoRoman",128,152.381,chars};
